# definir el alcance de los hosts
- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars_files:
    - vars/vars-site.yml
  tasks:
    - name: Instalar servicio Apache
      include_tasks: includes/install-apache2.yml
    - name: crear directorio para el sitio
      include_tasks: includes/create-directory.yml
    - name: copiar index.html al directorio del sitio
      include_tasks: includes/copy-index.yml
    - name: Configuracion del sitio apache y Activacion del nuevo sitio
      include_tasks: includes/config-and-activate.yml
    - name: Deshabilita el sitio default
      command: a2dissite 000-default.conf
      notify:
        - Reload Apache
      when: is_ubuntu
    - name: Cambiar el e-mail del webmaster
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'ServerAdmin webmaster@localhost'
        line: '	ServerAdmin webmaster@educacionit.com'
      when: is_ubuntu
      notify:
      - Reload Apache
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
      when: is_ubuntu